version: "3"

services:
  app:
    build:
      context: flask
    deploy:
      replicas: 2
    ports:
      - "5000"
  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
